

//signup
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"


//login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

//user load
export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST"
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
export const USER_LOAD_FAILURE = "USER_LOAD_FAILURE"

// error
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST"
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS"
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE"





// ##### POSTS ########
// post loading
export const POSTS_LOADING_REQUEST = "POSTS_LOADING_REQUEST"
export const POSTS_LOADING_SUCCESS = "POSTS_LOADING_SUCCESS"
export const POSTS_LOADING_FAILURE = "POSTS_LOADING_FAILURE"

// post upload 
export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST"
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS"
export const UPLOAD_POST_FAILURE = "UPLOAD_POST_FAILURE"

// post page detail
export const POST_DETAIL_LOADING_REQUEST = "POST_DETAIL_LOADING_REQUEST"
export const POST_DETAIL_LOADING_SUCCESS = "POST_DETAIL_LOADING_SUCCESS"
export const POST_DETAIL_LOADING_FAILURE = "POST_DETAIL_LOADING_FAILURE"

//post delete
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE"

// write
export const POST_WRITE_REQUEST = "POST_WRITE_REQUEST"
export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS"
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE"

// comments
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST"
export const COMMENT_LOADING_SUCCESS = "COMMENT_LOADING_SUCCESS"
export const COMMENT_LOADING_FAILURE = "COMMENT_LOADING_FAILURE"

export const COMMENT_UPLOADING_REQUEST = "COMMENT_UPLOADING_REQUEST"
export const COMMENT_UPLOADING_SUCCESS = "COMMENT_UPLOADING_SUCCESS"
export const COMMENT_UPLOADING_FAILURE = "COMMENT_UPLOADING_FAILURE"

// comment edit
export const COMMENT_EDIT_REQUEST = "COMMENT_EDIT_REQUEST"
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS"
export const COMMENT_EDIT_FAILURE = "COMMENT_EDIT_FAILURE"

// comment delete
export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST"
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS"
export const COMMENT_DELETE_FAILURE = "COMMENT_DELETE_FAILURE"


// post loading edit 
export const POST_EDIT_LOADING_REQUEST = "POST_EDIT_LOADING_REQUEST"
export const POST_EDIT_LOADING_SUCCESS = "POST_EDIT_LOADING_SUCCESS"
export const POST_EDIT_LOADING_FAILURE = "POST_EDIT_LOADING_FAILURE"

// post uploading edit 
export const POST_EDIT_UPLOADING_REQUEST = "POST_EDIT_UPLOADING_REQUEST"
export const POST_EDIT_UPLOADING_SUCCESS = "POST_EDIT_UPLOADING_SUCCESS"
export const POST_EDIT_UPLOADING_FAILURE = "POST_EDIT_UPLOADING_FAILURE"


// post uploading edit 
export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST"
export const CATEGORY_FIND_SUCCESS = "CATEGORY_FIND_SUCCESS"
export const CATEGORY_FIND_FAILURE = "CATEGORY_FIND_FAILURE"

// post uploading edit 
export const SEARCH_REQUEST = "SEARCH_REQUEST"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILURE = "SEARCH_FAILURE"


// password change
export const PASSWORD_CHANGE_REQUEST = "PASSWORD_CHANGE_REQUEST"
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS"
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE"


// recomment
export const RECOMMENT_UPLOAD_REQUEST = "RECOMMENT_UPLOAD_REQUEST"
export const RECOMMENT_UPLOAD_SUCCESS = "RECOMMENT_UPLOAD_SUCCESS"
export const RECOMMENT_UPLOAD_FAILURE = "RECOMMENT_UPLOAD_FAILURE"